"""QA tests for weather-public.json export — plan: qa-public-weather-backend.

Verifies that export() produces a weather-public.json with the correct schema:
- schema_version == 2
- property_meta is a dict with temp_indoor and temp_outdoor keys
- predictions is a list
- next_prediction is a dict or None
- current has a readings dict
- history and feature_rankings are absent
"""
import json
import os
import sys
import tempfile

SCRIPT_DIR = os.path.join(os.path.dirname(__file__), '..', 'the-snake-tank')
sys.path.insert(0, os.path.abspath(SCRIPT_DIR))

import export_weather


def _run_export():
    """Run export() into a temp dir and return the parsed weather-public.json."""
    with tempfile.TemporaryDirectory() as tmpdir:
        output_path = os.path.join(tmpdir, 'weather.json')
        try:
            export_weather.export(output_path, hours=24)
        except Exception:
            pass  # export may warn about missing R2 creds — that's fine
        public_path = os.path.join(tmpdir, 'weather-public.json')
        if not os.path.exists(public_path):
            return None
        with open(public_path) as f:
            return json.load(f)


_PUBLIC = _run_export()


def test_schema_version():
    """schema_version equals 2."""
    assert _PUBLIC is not None, "weather-public.json was not generated by export()"
    assert _PUBLIC.get('schema_version') == 2, \
        f"Expected schema_version 2, got {_PUBLIC.get('schema_version')}"


def test_property_meta_structure():
    """property_meta is a dict with temp_indoor and temp_outdoor keys."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    meta = _PUBLIC.get('property_meta')
    assert isinstance(meta, dict), f"property_meta is not a dict: {type(meta)}"
    assert 'temp_indoor' in meta, f"property_meta missing temp_indoor: {list(meta.keys())}"
    assert 'temp_outdoor' in meta, f"property_meta missing temp_outdoor: {list(meta.keys())}"


def test_predictions_is_list():
    """predictions is a list."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    preds = _PUBLIC.get('predictions')
    assert isinstance(preds, list), f"predictions is not a list: {type(preds)}"


def test_next_prediction_is_dict_or_none():
    """next_prediction is a dict or None."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    np = _PUBLIC.get('next_prediction')
    assert np is None or isinstance(np, dict), \
        f"next_prediction is neither dict nor None: {type(np)}"


def test_current_has_readings():
    """current has a readings dict."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    current = _PUBLIC.get('current')
    assert isinstance(current, dict), f"current is not a dict: {type(current)}"
    readings = current.get('readings')
    assert isinstance(readings, dict), f"current.readings is not a dict: {type(readings)}"


def test_history_absent():
    """history key is absent from weather-public.json."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    assert 'history' not in _PUBLIC, \
        f"history should not be in weather-public.json, but found it"


def test_feature_rankings_absent():
    """feature_rankings key is absent from weather-public.json."""
    assert _PUBLIC is not None, "weather-public.json was not generated"
    assert 'feature_rankings' not in _PUBLIC, \
        f"feature_rankings should not be in weather-public.json, but found it"
